const tags = [
  "Fluff",
  "Angst",
  "Smut",
  "Hurt/Comfort",
  "Romance",
  "Established Relationship",
  "Alternate Universe",
  "One Shot",
  "Humor",
  "Cute",
  "Anal Sex",
  "Alternate Universe - Modern Setting",
  "Slow Burn",
  "Oral Sex",
  "Friends to Lovers",
  "First Kiss",
  "Pining",
  "First Time",
  "Crossover",
  "Canon Compliant",
  "Kissing",
  "Short",
  "Domestic Fluff",
  "Blow Jobs",
  "Light Angst",
  "Post-Canon",
  "Alternate Universe - College/University",
  "Family",
  "PWP",
  "Explicit Sexual Content",
  "Violence",
  "Time Travel",
  "Masturbation",
  "Dirty Talk",
  "Sex",
  "Mpreg",
  "Rough Sex",
  "Character Study",
  "Character Death",
  "Sweet",
  "Depression",
  "Falling In Love",
  "Alternate Universe - High School",
  "NSFW",
  "Polyamory",
  "Christmas",
  "Rimming",
  "Soulmates",
  "Porn",
  "Blood",
  "Sexual Content",
  "Magic",
  "Sad",
  "BDSM",
  "Jealousy",
  "Developing Relationship",
  "Vaginal Sex",
  "Funny",
  "Dom/sub",
  "Minor Character Death",
  "Slice of Life",
  "Dubious Consent",
  "Misunderstandings",
  "Spanking",
  "Future Fic",
  "Kidnapping",
  "Comfort",
  "Unrequited Love",
  "Nightmares",
  "Flirting",
  "Kid Fic",
  "Pre-Canon",
  "Long",
  "Fix-It",
  "Pre-Slash",
  "Pre-Relationship",
  "Torture",
  "Teasing",
  "Suicidal Thoughts",
  "Explicit Language",
  "Alcohol",
  "Anxiety",
  "Crying",
  "Bondage",
  "Action/Adventure",
  "Alternate Universe - Fantasy",
  "Heavy Angst",
  "Daddy Kink",
  "Modern AU",
  "Friendship/Love",
  "Cunnilingus",
  "First Meetings",
  "Slow Build",
  "Domestic",
  "Age Difference",
  "Porn With Plot",
  "Voyeurism",
  "Murder",
  "Coming Out",
  "Incest",
  "Introspection",
  "Self-Harm",
  "Sex Toys",
  "Pregnancy",
  "Secret Relationship",
  "Semi-Public Sex",
  "Drinking",
  "Christmas Fluff",
  "Gay",
  "Vampires",
  "Sharing a Bed",
  "Sibling Incest",
  "Threesome - M/M/M",
  "Frottage",
  "Poetry",
  "Fake/Pretend Relationship",
  "Abuse",
  "Flashbacks",
  "Marriage Proposal",
  "POV First Person",
  "Blood and Gore",
  "Biting",
  "Hurt",
  "Fantasy",
  "Horror",
  "Multiple Orgasms",
  "Found Family",
  "Mystery",
  "Making Out",
  "Boys In Love",
  "Threesome",
  "Homophobia",
  "Light Bondage",
  "Banter",
  "Reincarnation",
  "Possessive Behavior",
  "Drug Use",
  "Trauma",
  "Loss of Virginity",
  "Past Relationship(s)",
  "Not Canon Compliant",
  "Bullying",
  "Confessions",
  "Friends With Benefits",
  "Best Friends",
  "High School",
  "Unresolved Sexual Tension",
  "Exhibitionism",
  "Internalized Homophobia",
  "Public Sex",
  "Cheating",
  "Past Abuse",
  "Arranged Marriage",
  "Humiliation",
  "Fluffy",
  "Aftercare",
  "Threesome - F/M/M",
  "Crossdressing",
  "Choking",
  "Amnesia",
  "Dancing",
  "Alcohol Abuse/Alcoholism",
  "Minor Violence",
  "Overstimulation",
  "War",
  "Recovery",
  "Trans Character",
  "Healing",
  "Memory Loss",
  "Supernatural Elements",
  "Break Up",
  "Underage Drinking",
  "Femslash",
  "Werewolves",
  "Ghosts",
  "Chaptered",
  "True Love",
  "Guilt",
  "Light BDSM",
  "Self-Esteem Issues",
  "Texting",
  "Barebacking",
  "Cuddling",
  "Reunions",
  "Family Drama",
  "Demons",
  "Father-Son Relationship",
  "Tragedy",
  "Unhealthy Relationships",
  "Recreational Drug Use",
  "College AU",
  "Pain",
  "Canon Universe",
  "Gore",
  "Weddings",
  "Memories",
  "POV Outsider",
  "Alternate Universe - Vampire",
  "POV Alternating",
  "Shower Sex",
  "Sad Ending",
  "Begging",
  "Secrets",
  "Manipulation",
  "Insecurity",
  "Smoking",
  "Size Kink",
  "Double Penetration",
  "Post-War",
  "Riding",
  "Nipple Play",
  "Alternate Universe - Canon",
  "Bonding",
  "PTSD",
  "Alternate Universe - Historical",
  "Betrayal",
  "Temporary Character Death",
  "Hopeful Ending",
  "Infidelity",
  "Adoption",
  "One-Sided Attraction",
  "Heartbreak",
  "Underage Sex",
  "Drugs",
  "Fingering",
  "Holidays",
  "Roommates",
  "Bittersweet",
  "Mutual Masturbation",
  "Unplanned Pregnancy",
  "Revenge",
  "Protectiveness",
  "Mind Control",
  "Awkwardness",
  "Music",
  "Arguing",
  "Asexual Character",
  "Drunk Sex",
  "Headcanon",
  "Prostitution",
  "Worldbuilding",
  "Hair-pulling",
  "Dreams",
  "Teacher-Student Relationship",
  "POV Third Person",
  "Unhealthy Coping Mechanisms",
  "Tattoos",
  "Past Character Death",
  "Dragons",
  "Secret Identity",
  "Scars",
  "Vomiting",
  "Slavery",
  "Tentacles",
  "Politics",
  "Lingerie",
  "First Love",
  "Brothers",
  "Non-Graphic Violence",
  "Blowjobs",
  "Alternate Universe - Magic",
  "Genderswap",
  "Genderbending",
  "Fights",
  "Alternate Universe - Gender Changes",
  "Dysfunctional Family",
  "Cuddles",
  "Minor Injuries",
  "Declarations Of Love",
  "Mild Gore",
  "Phone Sex",
  "Fingerfucking",
  "Love/Hate",
  "Mental Instability",
  "Loneliness",
  "Lesbian Sex",
  "Witches",
  "Families of Choice",
  "Parenthood",
  "Teen Romance",
  "Soul Bond",
  "Anal",
  "Children",
  "Science Fiction",
  "Love at First Sight",
  "Deepthroating",
  "Non-Consensual Drug Use",
  "Blindfolds",
  "Collars",
  "Punishment",
  "Vignette",
  "Forbidden Love",
  "Winter",
  "Babies",
  "Post-Break Up",
  "Femdom",
  "Fear",
  "Marking",
  "Unreliable Narrator",
  "Dating",
  "Accidental Voyeurism",
  "Anger",
  "Cooking",
  "Breathplay",
  "Sexual Fantasy",
  "Siblings",
  "Alternate Universe - Hogwarts",
  "Long-Distance Relationship",
  "Cannibalism",
  "Growing Up",
  "Therapy",
  "Coming of Age",
  "Stalking",
  "High School AU",
  "Watersports",
  "Bathing/Washing",
  "Loss",
  "Car Sex",
  "Royalty",
  "Handcuffs",
  "Orgasm Denial",
  "Father-Daughter Relationship",
  "Letters",
  "Anal Play",
  "Pegging",
  "Roleplay",
  "Trust Issues",
  "Late Night Conversations",
  "Insomnia",
  "Butt Plugs",
  "Regret",
  "Guns",
  "Comfort/Angst",
  "Power Dynamics",
  "Massage",
  "Hate Sex",
  "Switching",
  "Stockholm Syndrome",
  "Non-Linear Narrative",
  "Alternate Canon",
  "Redemption",
  "Time Skips",
  "Historical",
  "Magical Realism",
  "Wall Sex",
  "Bisexuality",
  "Verbal Humiliation",
  "Sex Pollen",
  "Forced Orgasm",
  "One Night Stands",
  "Nudity",
  "Outdoor Sex",
  "Rescue",
  "Restraints",
  "Gay Male Character",
  "Rope Bondage",
  "Drug Addiction",
  "Gags",
  "Alternate Universe - Superheroes/Superpowers",
  "Baking",
  "Party",
  "Gangbang",
  "Character Development",
  "Rain",
  "Angels",
  "New Year's Eve",
  "Holding Hands",
  "Resolved Sexual Tension",
  "Knifeplay",
  "Caretaking",
  "Transformation",
  "Apocalypse",
  "Somnophilia",
  "Seduction",
  "Self-Doubt",
  "Child Neglect",
  "Embarrassment",
  "Bromance",
  "Wings",
  "Office Sex",
  "Tears",
  "Post-Apocalypse",
  "Possession",
  "Telepathy",
  "Reconciliation",
  "Awkward Conversations",
  "Murder Mystery",
  "Mild Angst",
  "Mythical Beings & Creatures",
  "Dildos",
  "Facials",
  "Mistletoe",
  "Shapeshifting",
  "Sexual Abuse",
  "Bickering",
  "Masochism",
  "Alternate Universe - Dark",
  "Bisexual Male Character",
  "Sadism",
  "Summer",
  "Zombies",
  "Wedding",
  "Rape Recovery",
  "Morning Sex",
  "Bloodplay",
  "Time Loop",
  "Canon Related",
  "Twincest",
  "Blackmail",
  "Edging",
  "Alternate Universe - Fairy Tale",
  "Engagement",
  "Bathroom Sex",
  "Prison",
  "School",
  "Some angst",
  "Tickling",
  "Power Play",
  "Kink Negotiation",
  "Intercrural Sex",
  "Submission",
  "Romantic Friendship",
  "Vacation",
  "Denial",
  "Clothed Sex",
  "Religion",
  "Age Play",
  "Brainwashing",
  "Angry Sex",
  "Morning After",
  "Immortality",
  "Twins",
  "Pirates",
  "Animal Transformation",
  "Threesome - F/F/M",
  "Living Together",
  "Intimacy",
  "Alternate Reality",
  "Master/Slave",
  "Awkward Sexual Situations",
  "Domestic Bliss",
  "Tentacle Sex",
  "Drowning",
  "Camping",
  "Sexual Slavery",
  "Divorce",
  "World War II",
  "Orgasm Control",
  "Childbirth",
  "Identity Issues",
  "Touching",
  "Miscarriage",
  "Unsafe Sex",
  "Chatting & Messaging",
  "Hockey",
  "handjobs",
  "Zombie Apocalypse",
  "Enthusiastic Consent",
  "Afterlife",
  "Aphrodisiacs",
  "Resurrection",
  "Unhappy Ending",
  "Stargazing",
  "Alternate Universe - Science Fiction",
  "Non-Explicit Sex",
  "One-Sided Relationship",
  "Plot What Plot",
  "Whipping",
  "Verbal Abuse",
  "Illnesses",
  "Comeplay",
  "Rivalry",
  "Drunken Shenanigans",
  "Drug Abuse",
  "Original Fiction",
  "Aftermath of Violence",
  "Poly",
  "Alternate Universe - Office",
  "Power Imbalance",
  "Clubbing",
  "69 (Sex Position)",
  "Orgy",
  "Daddy Issues",
  "Insanity",
  "Truth or Dare",
  "Apologies",
  "Alternate Universe - Space",
  "Movie Night",
  "Sleeping Together",
  "Reunion",
  "First Date",
  "Role Reversal",
  "Pregnant Sex",
  "Wet Dream",
  "Fisting",
  "Face Slapping",
  "Mafia AU",
  "Sappy",
  "Bodyswap",
  "Get Together",
  "Casual Sex",
  "Brother-Sister Relationships",
  "Medical Procedures",
  "Superheroes",
  "Ambiguous Relationships",
  "Undercover",
  "Cock Rings",
  "Matchmaking",
  "Foreplay",
  "Asphyxiation",
  "Edgeplay",
  "Group Sex",
  "Light-Hearted",
  "Serial Killers",
  "Sleep Deprivation",
  "Unprotected Sex",
  "Human Experimentation",
  "Alternate Universe - Rock Band",
  "Forced Marriage",
  "No Dialogue",
  "Social Anxiety",
  "Young Love",
  "Dream Sex",
  "Desk Sex",
  "Consent Issues",
  "Thriller",
  "Babysitting",
  "Oblivious",
  "Topping from the Bottom",
  "Reminiscing",
  "Mental Illness",
  "Mistaken Identity",
  "Mind Games",
  "Making Up",
  "Piercings",
  "Military",
  "Coma",
  "Diary/Journal",
  "Police",
  "Fake Marriage",
  "Fantasizing",
  "Baby",
  "Marijuana",
  "Cultural Differences",
  "Origin Story",
  "Sparring",
  "Love Bites",
  "Codependency",
  "Longing",
  "Sensory Deprivation",
  "Licking",
  "Bad Parenting",
  "Dom/sub Play",
  "5 Times",
  "Fuck Or Die",
  "Closeted Character",
  "Shopping",
  "Photography",
  "Painplay",
  "Addiction",
  "Comfort Sex",
  "Dysfunctional Relationships",
  "Courtship",
  "Self-Sacrifice",
  "Foot Fetish",
  "Porn Without Plot",
  "Alternate Universe - Angels & Demons",
  "Abandonment",
  "Public Humiliation",
  "Blind Date",
  "Sex Work",
  "Sports",
  "Growing Up Together",
  "Voice Kink",
  "Drugged Sex",
  "Teen Pregnancy",
  "Sacrifice",
  "Exhaustion",
  "Requited Love",
  "Hospital",
  "Cock Worship",
  "Object Insertion",
  "Detectives",
  "Psychic Abilities",
  "Vampire AU",
  "Hotel Sex",
  "Wedding Night",
  "Public Display of Affection",
  "Amputation",
  "Heartache",
  "Safewords",
  "Robots",
  "injuries",
  "Huddling For Warmth",
  "Showers",
  "Dystopia",
  "Lactation Kink",
  "Stripping",
  "Competition",
  "Bad Decisions",
  "Snowed In",
  "Adultery",
  "Swimming",
  "Crime",
  "Pet Play",
  "Beaches",
  "London",
  "Vampire Sex",
  "Mermaids",
  "Marriage of Convenience",
  "First Times",
  "Fatherhood",
  "Cigarettes",
  "Disturbing Themes",
  "Sibling Rivalry",
  "Dirty Thoughts",
  "Threesome - F/F/F",
  "Snowball Fight",
  "Field Trip",
  "Fake Relationship",
  "Forced Pregnancy",
  "Rejection",
  "Kitchen Sex",
  "Creature Fic",
  "Exes",
  "Alternate Universe - Gangsters",
  "Sexual Harassment",
  "Hypnotism",
  "Drinking Games",
  "Potions",
  "Manhandling",
  "Paranormal",
  "Explosions",
  "Mindfuck",
  "Rituals",
  "Couch Sex",
  "Possessive Sex",
  "non-con",
  "Heaven",
  "5+1",
  "Villains",
  "Breakup",
  "Multiple Partners",
  "Road Trip",
  "Artificial Intelligence",
  "Pillow Talk",
  "Muteness",
  "New Years",
  "Medical Kink",
  "Quarantine",
  "Interrogation",
  "Public Nudity",
  "Moral Ambiguity",
  "Temperature Play",
  "Late at Night",
  "Felching",
  "Non-Consensual Spanking",
  "Multiple Pairings",
  "Sleepy Sex",
  "Non-Consensual",
  "Grooming",
  "Crush",
  "Flogging",
  "Alternate Universe - Regency",
  "Older Woman/Younger Man",
  "Mental Anguish",
  "Condoms",
  "Strip Tease",
  "Band Fic",
  "Bath Sex",
  "Accidental Marriage",
  "Yearning",
  "Greek Mythology - ",
  "Master/Servant",
  "Objectification",
  "Personal Growth",
  "Prophecy",
  "Fate",
  "Secret Admirer",
  "Sexual Experimentation",
  "Gambling",
  "Cuckolding",
  "Picnics",
  "Food Sex",
  "Love Potion/Spell",
  "Cousin Incest",
  "Porn Battle",
  "Hair Pulling",
  "Mommy Kink",
  "Bad BDSM Etiquette",
  "Necromancy",
  "Deception",
  "dub-con",
  "Forced Bonding",
  "Intersex",
  "Orphans",
  "Espionage",
  "Heroes",
  "Parents",
  "Forced Prostitution",
  "Football",
  "Sexism",
  "Self-cest",
  "Piano",
  "Fuckbuddies",
  "Chains",
  "Coercion",
  "Alternate Universe - Western",
  "Partnership",
  "Leashes",
  "Roughness",
  "Kidnapped",
  "Strangers",
  "Motorcycles",
  "Non-Penetrative Sex",
  "Baseball",
  "Love Triangle",
  "Friends to Enemies",
  "Tearjerker",
  "Sneaking Around",
  "Sister-Sister Relationship",
  "Fairies",
  "Enemies",
  "Experimental Style",
  "Ass to Mouth",
  "Demon",
  "Desire",
  "Frustration",
  "Caning",
  "Alternate Universe - Criminals",
  "True Love's Kiss",
  "Alternate Universe - Boarding School",
  "Curtain Fic",
  "Open Ending",
  "Sharing Body Heat",
  "Marathon Sex",
  "Teaching",
  "Succubi & Incubi",
  "Victorian",
  "Rape Fantasy",
  "Violent Sex",
  "Heist",
  "Porn Watching",
  "Alternate Universe - Shapeshifters",
  "Table Sex",
  "Hand Job",
  "Homecoming",
  "Moral Dilemmas",
  "Boarding School",
  "Kneeling",
  "Hickeys",
  "World War I",
  "Lapdance",
  "Affairs",
  "Fucking Machines",
  "Emotional Abuse",
  "Secret Marriage",
  "Premature Ejaculation",
  "Attempted Suicide",
  "Dark Fantasy",
  "Molestation",
  "Abuse of Authority",
  "Sweat",
  "Clothing Kink",
  "Theatre",
  "Library",
  "Spin the Bottle",
  "Gaming",
  "Napping",
  "Glory Hole",
  "One Night Stand",
  "Snowballing",
  "Skinny Dipping",
  "Wrestling",
  "Theft",
  "Accidental Bonding",
  "Beach Sex",
  "Trains",
  "Drug Dealing",
  "Partner Betrayal",
  "Traditions",
  "Stranded",
  "Anonymous Sex",
  "Undressing",
  "Psychic Bond",
  "Students",
  "Opposites Attract",
  "Boys in Skirts",
  "Cock Tease",
  "Control",
  "Truth Serum",
  "Regency",
  "Breaking and Entering",
  "Yakuza",
  "Bathtubs",
  "Pain Kink",
  "Delusions",
  "face fucking",
  "Ice Play",
  "Sexual Inexperience",
  "Age Swap",
  "Vikings",
  "Boys Being Boys",
  "Workplace Sex",
  "Bottoming from the Top",
  "Alternate Universe - Restaurant",
  "Eavesdropping",
  "Modeling",
  "Bedroom Sex",
  "Uniform Kink",
  "Dirty Dancing",
  "Virtual Reality",
  "Closet Sex",
  "Knights",
  "Hypnosis",
  "Infertility",
  "Space Pirates",
  "Dress Up",
  "1980s",
  "1920s",
  "Prison Sex",
  "Alternate Universe - Politics",
  "Sensation Play",
  "Spies",
  "Baby Fic",
  "Pheromones",
  "Hiking",
  "Gothic",
  "Worship",
  "Unrequited Lust",
  "Obedience",
  "Acting",
  "Ownership",
  "Christianity",
  "1960s",
  "1970s",
  "Olympics",
  "Summer Camp",
  "Library Sex",
  "Snuggling",
  "Yoga",
  "Wooing",
  "Harassment",
  "Lovers",
  "Sex Club",
  "Play Fighting",
  "Alternate Universe - Small Town",
  "Locker Room",
  "Fondling",
  "Self-Loathing",
  "Legends",
  "Prayer",
  "Revenge Sex",
  "1930s",
  "Priest Kink",
  "Watching Someone Sleep",
  "Nipple Torture",
  "Tarot",
  "Tsunderes",
  "Humiliation kink",
  "Bitterness",
  "Medieval",
  "1950s",
  "Martial Arts",
  "Mind Reading",
  "Domination",
  "Stalker",
  "Church Sex",
  "Bad Sex",
  "Fight Sex",
  "Sexual Confusion",
  "Sleepwalking",
  "Tattoos",
  "Pool Sex",
  "Board Games",
  "Quiet Sex",
  "Candles",
  "Mile High Club",
  "Non-Sexual Kink",
  "Elevator Sex",
  "Biblical References",
  "Object Penetration",
  "Nobility",
  "Power Outage",
  "Aliens Made Them Do It",
  "Porn Video",
  "Phone Calls",
  "Cockblocking",
  "Obliviousness",
  "Priests",
  "Telepathic Sex",
  "Desert",
  "Street Racing",
  "Goddesses",
  "Dare",
  "Facial",
  "Regency Romance",
  "Fear Play",
  "Plague",
  "Wounds",
  "Underworld",
  "Fame",
  "Poker",
  "Surfing",
  "April Fools' Day",
  "Catholicism",
  "Service Submission",
  "Underwear",
  "Fever Dreams",
  "Centaurs",
  "Sailing",
  "Classroom Sex",
  "Atlantis",
  "Cohabitation",
  "Judaism",
  "selective mutism",
  "Body Paint",
  "body image issues",
  "Rock Stars",
  "Teacher/Student",
  "M/M/M",
  "Armpit Kink",
  "Con Artists",
  "Disassociation",
  "Underwear Kink",
  "Natural Disasters",
  "Bus",
  "Platonic Love",
  "Regeneration",
  "Descent into Madness",
  "Bathing",
  "Emo",
  "Nursing",
  "Strip Poker",
  "Strip Poker",
  "Body Hair",
  "Locked In",
  "Mad Scientists",
  "Sex Games",
  "Lazy Sex",
  "Rough Sex",
  "Alpha/Beta/Omega Dynamics",
  "Scent kink",
  "Awkward Boners",
  "Phone Sex",
  "Sexting",
  "Breeding Kink",
  "Enemies to Lovers",
  "Boypussy",
  "Stomach Bulge",
  "Rimming",
  "Drunken Flirting",
  "Mating Cycles/In Heat",
  "Loss of Innocence",
  "Voyeurism",
  "Dead Dove: Do Not Eat",
  "Dry Humping",
  "Neediness",
  "Deal with the Devil",
  "Size Difference",
  "Size Kink",
];

function generate() {
  var selectedNum = document.getElementById("num_tags");
  var numTags = Number(selectedNum.value);
  var span = document.querySelector(".ao3-tag-style");

  if (numTags < 0) {
    span.innerText = "a negative number? fr?";
  } else if (numTags == 0) {
    span.innerText = "you get nothing!";
  } else if (numTags > 50) {
    span.innerText = "more than 50 is just excessive";
  } else {
    arr = getRandom(tags, numTags);

    span.innerText = arr.join(", ");
  }
}

// kudos btn
function gratitude() {
  let msgElement = document.querySelector(".user_liked");
  msgElement.innerText = "You";
}

// share btn
function share() {
  let url = "https://taggenerator.netlify.app/";
  try {
    copyToClipboard(url);
    console.log("Text copied to the clipboard");
  } catch (error) {
    console.error(error);
  }
}

async function copyToClipboard(textToCopy) {
  // Navigator clipboard api needs a secure context (https)
  if (navigator.clipboard && window.isSecureContext) {
    await navigator.clipboard.writeText(textToCopy);
  } else {
    // Use the 'out of viewport hidden text area' trick
    const textArea = document.createElement("textarea");
    textArea.value = textToCopy;

    // Move textarea out of the viewport so it's not visible
    textArea.style.position = "absolute";
    textArea.style.left = "-999999px";

    document.body.prepend(textArea);
    textArea.select();

    try {
      document.execCommand("copy");
    } catch (error) {
      console.error(error);
    } finally {
      textArea.remove();
    }
  }
}

//  function posted by Bergi on https://stackoverflow.com/questions/19269545/how-to-get-a-number-of-random-elements-from-an-array
function getRandom(arr, n) {
  var result = new Array(n),
    len = arr.length,
    taken = new Array(len);
  if (n > len)
    throw new RangeError(
      "getRandom: n cannot be greater than length of array."
    );
  while (n--) {
    var x = Math.floor(Math.random() * len);
    result[n] = arr[x in taken ? taken[x] : x];
    taken[x] = --len in taken ? taken[len] : len;
  }
  return result;
}

var input = document.getElementById("num_tags");
input.addEventListener("keypress", function (event) {
  if (event.key === "Enter") {
    document.getElementById("gen-btn").click();
  }
});

// customize values in work info box
var custParent = document.querySelector(".cust_input_parent");
custParent.addEventListener("click", changeValue, false);
function changeValue(e) {
  if (e.target !== e.currentTarget) {
    var clickedItem = e.target.id;
    if (clickedItem != "") {
      //   alert(e.target.innerText);
      var custInput = prompt("Enter new value");
      if (custInput) {
        console.log(this);
        e.target.innerText = custInput;
      }
    }
  }
  e.stopPropagation();
}

// change title
function changeTitle() {
  var title = document.querySelector("#cust_title");
  var newTitle = prompt("Enter new value.");
  if (newTitle) {
    title.innerText = newTitle;
  }
}

// add your own ao3 username!
function changeUser() {
  var custUser = prompt("Enter an ao3 username.");
  if (custUser) {
    authField = document.querySelector("#work_auth");
    authField.innerText = custUser;
    newUrl = "https://archiveofourown.org/users/" + custUser;
    authField.setAttribute("href", newUrl);
  }
}
